config/routes.rb
Rails.application.routes.draw do
  

  resources :shoplocations
  resources :shoptimings
  resources :shopphotos
  devise_for :users

  authenticated :user do
    root 'home#dashbord', as: :authenticated_root
  end
  root 'home#index'
  
 resources :shopaddresses
 resources :shopabouts

 get '/search' => "home#search"
 get '/about_us' => "home#about_us"
 get '/contact_us' => "home#contact_us"
 get '/privacy_policy' => "home#privacy_policy"
 get '/termandcondition' => "home#termandcondition"
  

  

end

app/controllers/shopaddresses_controller.rb
class ShopaddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shopaddress, only: [:show, :edit, :update, :destroy]

  # GET /shopaddresses
  # GET /shopaddresses.json
  def index
    @shopaddresses = current_user.shopaddresses
    if Shopaddress.where(:user_id => current_user.id).present?
         shopaddresses_path
     else
          redirect_to new_shopaddress_path
    end    
  end

  # GET /shopaddresses/1
  # GET /shopaddresses/1.json
  def show
  end

  # GET /shopaddresses/new
  def new
    @shopaddress = Shopaddress.new
  end

  # GET /shopaddresses/1/edit
  def edit
  end

  # POST /shopaddresses
  # POST /shopaddresses.json
  def create
    @shopaddress = Shopaddress.new(shopaddress_params)
    @shopaddress.user_id = current_user.id

    respond_to do |format|
      if @shopaddress.save
        format.html { redirect_to shopaddresses_path, notice: 'Shopaddress was successfully created.' }
        format.json { render :show, status: :created, location: shopaddresses_path }
      else
        format.html { render :new }
        format.json { render json: shopaddresses_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopaddresses/1
  # PATCH/PUT /shopaddresses/1.json
  def update
    respond_to do |format|
      if @shopaddress.update(shopaddress_params)
        format.html { redirect_to shopaddresses_path, notice: 'Shopaddress was successfully updated.' }
        format.json { render :show, status: :ok, location: shopaddresses_path }
      else
        format.html { render :edit }
        format.json { render json: shopaddresses_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopaddresses/1
  # DELETE /shopaddresses/1.json
  def destroy
    @shopaddress.destroy
    respond_to do |format|
      format.html { redirect_to shopaddresses_url, notice: 'Shopaddress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopaddress
      @shopaddress = Shopaddress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopaddress_params
      params.require(:shopaddress).permit(:name, :streetaddress, :landmark, :city, :state, :pincode, :mobileno, :landlineno, :emailid, :websiteurl, :user_id)
    end
end

app/helpers/shopaddresses_helper.rb
module ShopaddressesHelper
end

app/views/shopaddresses/_form.html.erb
<section class="inner-banner light-black-bg">
  <div class="auto-container clearfix">
    <div class="title pull-left">
      <h3>Shop Address</h3>
    </div>
    <div class="breadcumb pull-right">
      <ul class="list-inline">
        <li><a href="/">Dashboard</a></li>
        <li><span>Shop Address</span></li>
      </ul>
    </div>
  </div>
</section>

<section class="get-a-qoute sec-padding">
  <div class="auto-container">
  <div class="row">

    <%= form_for(@shopaddress) do |f| %>
      <% if @shopaddress.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@shopaddress.errors.count, "error") %> prohibited this shopaddress from being saved:</h2>

          <ul>
          <% @shopaddress.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="col-sm-offset-1 col-md-5">
        <div class="form-group">
             <%= f.label :Shop_Name %>:
            <%= f.text_field :name, placeholder:" Shop Name", tabindex:"1" %>
        </div>
         <div class="form-group">
          <%= f.label :Shop_Email_Id %>:
            <%= f.text_field :emailid, placeholder:"Shop Email Id", tabindex:"2" %>
        </div>
          <div class="form-group">
           <%= f.label :Mobile_No %>:
            <%= f.text_field :mobileno, placeholder:"Shop Mobile No", tabindex:"3" %>
        </div>
          <div class="form-group">
           <%= f.label :Shop_landline_No %>:
            <%= f.text_field :landlineno, placeholder:"Shop landline No", tabindex:"4" %>
        </div>
         <div class="form-group">
          <%= f.label :Shop_Web_Site_Url %>:
             <%= f.text_field :websiteurl, placeholder:"Shop Web Site Url", tabindex:"5" %>
        </div>
        <div class="form-group">
         <%= f.label :Pin_Code %>:
            <%= f.text_field :pincode, placeholder:"Pin Code", tabindex:"6" %>
        </div>
        


        

      </div>
     
      <div class="col-md-5">
      <div class="form-group">
       <%= f.label :Street_Address %>:
            <%= f.text_area :streetaddress, placeholder:"Street Address", tabindex:"7" %>
        </div>
        <div class="form-group">
         <%= f.label :Landmark %>:
             <%= f.text_field :landmark, placeholder:" Landmark", tabindex:"8" %>
        </div>
        <div class="form-group">
         <%= f.label :City %>:
            <%= f.text_field :city, placeholder:"City", tabindex:"9" %>
        </div>
      <div class="form-group">
       <%= f.label :State %>:
           <%= f.text_field :state, placeholder:"State", tabindex:"10" %>
        </div>
       
       
        
        
       
        <div class="form-group clearfix">
         <%= f.submit class:"btn btn-success btn-lg", tabindex:"11"%>
         <%= link_to 'Back', shopaddresses_path, class:"btn  btn-lg", tabindex:"12" %>
         
        </div>
      </div>
     
      <!-- <div class=" col-sm-offset-4 col-md-12">
       
      </div> -->
     
     <% end %>
    </div>
  </div>
</section>

app/views/shopaddresses/edit.html.erb
<%= render 'form' %>
<!-- 
<%= link_to 'Show', @shopaddress %> 
<%= link_to 'Back', shopaddresses_path %>
 -->

app/views/shopaddresses/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Listing Shopaddresses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Streetaddress</th>
      <th>Landmark</th>
      <th>City</th>
      <th>State</th>
      <th>Pincode</th>
      <th>Mobileno</th>
      <th>Landlineno</th>
      <th>Emailid</th>
      <th>Websiteurl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shopaddresses.each do |shopaddress| %>
      <tr>
        <td><%= shopaddress.name %></td>
        <td><%= shopaddress.streetaddress %></td>
        <td><%= shopaddress.landmark %></td>
        <td><%= shopaddress.city %></td>
        <td><%= shopaddress.state %></td>
        <td><%= shopaddress.pincode %></td>
        <td><%= shopaddress.mobileno %></td>
        <td><%= shopaddress.landlineno %></td>
        <td><%= shopaddress.emailid %></td>
        <td><%= shopaddress.websiteurl %></td>
        <td><%= link_to 'Show', shopaddress %></td>
        <td><%= link_to 'Edit', edit_shopaddress_path(shopaddress) %></td>
        <td><%= link_to 'Destroy', shopaddress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopaddress', new_shopaddress_path %><br>
<%= link_to 'home', root_path %> -->

<!--  -->



<section class="inner-banner light-black-bg">
  <div class="auto-container clearfix">
    <div class="title pull-left">
      <h3>Shop Address Info.</h3>
    </div>
    <div class="breadcumb pull-right">
      <ul class="list-inline">
        <li><a href="/">Dashboard</a></li>
        <li><span>Shop Info.</span></li>
      </ul>
    </div>
  </div>
</section>
      





<% @shopaddresses.each do |shopaddress| %>
<section class="real-time-analytics sec-padding">
  <div class="auto-container">
    <div class="row">
    <div class="col-md-4">
        <div class="right-text">
         <h3>Name :</h3>
          <p><%= shopaddress.name %></p>

            <h3>Mobile No:</h3>
          <p><%= shopaddress.mobileno %></p>

           <h3>Landline No :</h3>
          <p><%= shopaddress.landlineno %></p>
         
          <h3>Email Id:</h3>
          <p><%= shopaddress.emailid %></p>

         
        
        </div>
      </div>
      <div class="col-md-4">
        <div class="right-text">
          
            <h3>Shop Address :</h3>
          <p><%= shopaddress.streetaddress %></p>
         
          
          <h3>Shop Landmark:</h3>
          <p><%= shopaddress.landmark %></p>

           <h3>City :</h3>
          <p><%= shopaddress.city %></p>

         
         
         

          
        </div>
      </div><!-- /.col-md-5 -->
      <div class="col-md-4">
        <div class="right-text">
         
          <h3>State:</h3>
          <p><%= shopaddress.state %></p>

           <h3>Pincode :</h3>
          <p><%= shopaddress.pincode %></p>
          
        

          <h3>WebSite url:</h3>
          <p><%= shopaddress.websiteurl %></p>
          

        </div>
      </div>

    </div><!-- /.row -->
  </div><!-- /.auto-container -->
      <div class="col-md-offset-4 col-md-6">
        <%= link_to 'Update Address', edit_shopaddress_path(shopaddress), class:" btn btn-lg btn-primary" %>
      </div>

</section>
<% end %>

app/views/shopaddresses/new.html.erb
<!-- <h1>New Shopaddress</h1> -->

<%= render 'form' %>

<%= link_to 'Back', shopaddresses_path %>

app/views/shopaddresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shopaddress.name %>
</p>

<p>
  <strong>Streetaddress:</strong>
  <%= @shopaddress.streetaddress %>
</p>

<p>
  <strong>Landmark:</strong>
  <%= @shopaddress.landmark %>
</p>

<p>
  <strong>City:</strong>
  <%= @shopaddress.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @shopaddress.state %>
</p>

<p>
  <strong>Pincode:</strong>
  <%= @shopaddress.pincode %>
</p>

<p>
  <strong>Mobileno:</strong>
  <%= @shopaddress.mobileno %>
</p>

<p>
  <strong>Landlineno:</strong>
  <%= @shopaddress.landlineno %>
</p>

<p>
  <strong>Emailid:</strong>
  <%= @shopaddress.emailid %>
</p>

<p>
  <strong>Websiteurl:</strong>
  <%= @shopaddress.websiteurl %>
</p>

<%= link_to 'Edit', edit_shopaddress_path(@shopaddress) %> |
<%= link_to 'Back', shopaddresses_path %>