config/routes.rb
Rails.application.routes.draw do
  

  resources :shoplocations
  resources :shoptimings
  resources :shopphotos
  devise_for :users

  authenticated :user do
    root 'home#dashbord', as: :authenticated_root
  end
  root 'home#index'
  
 resources :shopaddresses
 resources :shopabouts

 get '/search' => "home#search"
 get '/about_us' => "home#about_us"
 get '/contact_us' => "home#contact_us"
 get '/privacy_policy' => "home#privacy_policy"
 get '/termandcondition' => "home#termandcondition"
  

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
         @user= User.all
         @shopabouts = Shopabout.all   
      end
      def about_us
      	
      end
      def contact_us
      	
      end

      def privacy_policy
      	
      end
      def termandcondition
      	
      end
     
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_us.html.erb
<section class="inner-banner light-black-bg">
  <div class="auto-container clearfix">
    <div class="title pull-left">
      <h3>About Us</h3>
    </div>
    <div class="breadcumb pull-right">
      <ul class="list-inline">
        <li><a href="/">Dashboard</a></li>
        <li><span>About Us</span></li>
      </ul>
    </div>
  </div>
</section>

<section class="about-info sec-padding">
	<div class="auto-container">
		<div class="row">
			<div class="col-md-6">
				<div class="right-text">
					<div class="sec-title">
						
						<h3>Why We Create This Site</h3>						
					</div>
					<p>We developed a phased approach to do SEO. The SEO Workflow provides improvement tasks. Filtering and sorting options allows you to manage tasks fast and easy. The tasks are supported by clear problem description,</p>

					<h3>How To Use This Site</h3>			
					<p>WordPress users have unique guides to optimize for that CMS system.In SEO, it is important to not blindly start optimize your website on the keywords you want to rank for. There are competitors that also might optimize their websites. Knowing what makes your competitors show up high in the search engines.</p>
					
				</div>
			</div>	
			<div class="col-md-6">
				<div class="right-text">
					<div class="sec-title">
						
						<h3>How Is Help This Site For Shop</h3>						
					</div>
					<p>We developed a phased approach to do SEO. The SEO Workflow provides improvement tasks. Filtering and sorting options allows you to manage tasks fast and easy. The tasks are supported by clear problem description,</p>

					<h3>Why Choose This Site</h3>			
					<p>WordPress users have unique guides to optimize for that CMS system.In SEO, it is important to not blindly start optimize your website on the keywords you want to rank for. There are competitors that also might optimize their websites. Knowing what makes your competitors show up high in the search engines.</p>
					
				</div>
			</div>
		</div>
	</div>
</section>

app/views/home/contact_us.html.erb
<section class="inner-banner light-black-bg">
  <div class="auto-container clearfix">
    <div class="title pull-left">
      <h3>Contact Us</h3>
    </div>
    <div class="breadcumb pull-right">
      <ul class="list-inline">
        <li><a href="/">Dashboard</a></li>
        <li><span>Contact Us</span></li>
      </ul>
    </div>
  </div>
</section>

<div class="contact-page contact-form-wrapper sec-padding">
  <div class="auto-container">
    <div class="row">
      <div class="col-md-6">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d59601.02030907569!2d75.54031775797252!3d20.990080753240566!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bd90fa4a1eab90f%3A0x37f67bd21bff0a3c!2sJalgaon%2C+Maharashtra!5e0!3m2!1sen!2sin!4v1493041248204" width="580" height="550" frameborder="0" style="border:0" allowfullscreen></iframe>


      </div><!-- /.col-md-6 -->
      <div class="col-md-6">
        <div class="title">
          <h3>Get In Touch</h3>
        </div><!-- /.title -->
        <p>Consectetur adipiscing elit. Pellentesque lobortis, nisl at ullamcorper egestas, felis tortor adipiscing dolor, a interdum lorem urna quis magna. Integer eget arcu Integer eget arcu sit amet Integer commodo ipsum congue eu.</p>
        <form action="http://wp1.themexlab.com/html/digital-media/inc/sendemail.php" class="validate-cf contact-form">
          <input type="text" name="name"  placeholder="Name" />
          <input type="text" name="email"  placeholder="Email" />
          <textarea  name="message" placeholder="Message"></textarea>
          <button type="submit">Submit</button>
        </form>
      </div><!-- /.col-md-6 -->
    </div><!-- /.row -->
  </div><!-- /.auto-container -->
</div><!-- /.contact-page contact-form-wrapper -->

<section class="contact-info gray-bg">
  <div class="auto-container">
    <div class="row">
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="single-contact-info">
          <i class="flaticon-placeholder"></i>
          <h3>Where We Are?</h3>
          <p>2901 Marmora road, Glassgow, Seattle, WA 98122</p>
        </div><!-- /.single-contact-info -->
      </div><!-- /.col-md-3 -->
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="single-contact-info">
          <i class="flaticon-phone-call"></i>
          <h3>Give us a Call</h3>
          <p>Consectetuer ux adipis cing elit sed dolor sit amet.</p>
          <a href="#">+43 (0) 123 432 12 43</a>
        </div><!-- /.single-contact-info -->
      </div><!-- /.col-md-3 -->
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="single-contact-info">
          <i class="flaticon-technology"></i>
          <h3>Vist Our Office</h3>
          <p>Consectetuer ux adipis cing elit sed dolor sit amet.</p>
        </div><!-- /.single-contact-info -->
      </div><!-- /.col-md-3 -->
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="single-contact-info">
          <i class="flaticon-envelope-opened-outline"></i>
          <h3>Drop us a Line</h3>
          <p>2901 Marmora road, Glassgow, Seattle, WA 98122</p>
          <a href="#">Support@Digital.Com</a>
        </div><!-- /.single-contact-info -->
      </div><!-- /.col-md-3 -->
    </div><!-- /.row -->
  </div><!-- /.auto-container -->
</section><!-- /.contact-info -->

app/views/home/dashbord.html.erb
<section class="why-choose-us-two sec-padding">
	<div class="auto-container">
		<div class="row">
			<div class="col-md-6 col-sm-12 col-xs-12  pull-left">
					<ul class="why-choose-us-two-list">
					<li >
					<a href="/shopabouts">
						<div class="icon-box" >
							<img src="../assets/shop.png" style="color"  alt="Shop Info"/>
						</div><!-- /.icon-box -->
						<div class="text-box">
							<h3>Shop Info.</h3>
							<p>Add Your food Shop/ Medical Store/ Grocery Store/ Cycle Sale & Repairing/ Bike Sale & Repairing/ Mobile Shop/ Mobile Repairing/ footwear Store/ Footwear Repairing Store. all Shop About Information Save Here. </p>
						</div><!-- /.text-box --></a>
					</li>
					<li>
					  <a href="/shoptimings">
						<div class="icon-box">
							<img src="../assets/time.png" alt="Shop time"/>
						</div><!-- /.icon-box -->
						<div class="text-box">
							<h3>Shop Time</h3>
							<p>Add Your Shop Timing To See The client Shop Is Open Or Close & What Is The Timing</p>
						</div><!-- /.text-box -->
						</a>
					</li>
					<li>
					<a href="/shopphotos">
						<div class="icon-box">
							<img src="../assets/shop_image.png"  alt="Store Image"/>
						</div><!-- /.icon-box -->
						<div class="text-box">
							<h3>Shop Images</h3>
							<p>Here Save The Store Images To See The Clint</p>
						</div><!-- /.text-box -->
						</a>
					</li>
				</ul><!-- /.why-choose-us-two -->
			</div><!-- /.col-md-5 -->
			<div class="col-md-6 col-sm-12 col-xs-12 pull-right">
				<!-- <div class="sec-title light">
					<h3>Why Choose Digital Media</h3>col-xs-12
					<p>Grow your business and save time with seamless experience</p>
				</div> -->
				<ul class="why-choose-us-two-list">
					<li>
					<a href="/shopaddresses">
						<div class="icon-box">
							<img src="../assets/address.png"  alt="Address Info"/>
						</div><!-- /.icon-box -->
						<div class="text-box">
							<h3>Add Shop Address</h3>
							<p>Add Your food Shop/ Medical Store/ Grocery Store/ Cycle Sale & Repairing/ Bike Sale & Repairing/ Mobile Shop/ Mobile Repairing/ footwear Store/ Footwear Repairing Store. all Shop Address Information Save Here.</p>
						</div><!-- /.text-box -->
						</a>	
					</li>
					<li>
					<a href="/shoplocations">
						<div class="icon-box">
							<img src="../assets/map.png" alt="Map Location"/>
						</div><!-- /.icon-box -->
						<div class="text-box">
							<h3>Shop Map Location</h3>
							<p>Add your Shop Map Location. To find you Someone Quickly.</p><br>
						</div><!-- /.text-box -->
						</a>
					</li>
					<li>
					<a href="/shopaddresses">
						<div class="icon-box">
							<img src="../assets/comments.png"  alt="comments"/>
						</div><!-- /.icon-box -->
						<div class="text-box">
							<h3>Comments and Rating</h3>
							<p>client Giving To You Comments and Rating Your Store.</p>
						</div><!-- /.text-box -->
						</a>
					</li>
				</ul><!-- /.why-choose-us-two -->
			</div><!-- /.col-md-6 -->
		</div><!-- /.row -->
	</div><!-- /.auto-container -->
</section><!-- /.why-choose-us -->

app/views/home/index.html.erb
<div id="minimal-bootstrap-carousel" class="carousel slide carousel-fade shop-slider" data-ride="carousel">           
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active slide-1" style="background-image: url(../assets/worldmap.jpg);backgroudn-position: center right;">
            
            <div class="carousel-caption">
	      		<div class="thm-container">
	      			<div class="box valign-middle">
	      				<div class="content">
		      				 <div class="col-xs-8 col-xs-offset-2">
							    <div class="input-group">
					                <div class="input-group-btn search-panel">
					                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" style="height: 55px;">
					                    	<span id="search_concept">Filter by</span> <span class="caret"></span>
					                    </button>
					                    <ul class="dropdown-menu" role="menu">
					                      <li><a href="#">Grocery Store</a></li>
					                      <li><a href="#">Medical Store</a></li>
					                      <li><a href="#">Cycle & Bike Repairing</a></li>
					                      <li><a href="#">Mobile Shop & Repairing </a></li>
					                      <li><a href="#">footwear Repairing</a></li>
					                    </ul>
					                </div>
					                <input type="hidden" name="search_param" value="all" id="search_param">         
					                <input type="text" class="form-control" name="x" placeholder="Search your Destination..." style="height: 55px;">
					                <span class="input-group-btn">
					                    <button class="btn btn-success" type="button" style="height: 55px;width: 124px;"><i class="fa fa-search-plus" aria-hidden="true"></i></button>
					                </span>
					            </div>
                             </div>
                              <div class="col-xs-8 col-xs-offset-2">
		      				<div class="digital-banner-p" data-animation="animated fadeInDown">
		      				We use enterprise strategies to boost your local and worldwide<br>search rankings so your customers can find you when & where<br>they need</div></div>
		      			<!-- 	<a href="services.html" class="btn btn-default banner-btn" data-animation="animated zoomIn">Learn More</a>
 -->	      				</div>
	      			</div>
	      		</div>
	    	</div>                
        </div>
       
       
    </div>
   
   <!--  <a class="left carousel-control" href="#minimal-bootstrap-carousel" role="button" data-slide="prev">
        <i class="fa fa-angle-left"></i>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#minimal-bootstrap-carousel" role="button" data-slide="next">
        <i class="fa fa-angle-right"></i>
        <span class="sr-only">Next</span>
    </a> -->
</div>


<section class="promo-area sec-padding">
    <div class="auto-container">
        <div class="title">
            <h3>YOUR HOME THE WAY YOU'VE ALWAYS WANTED IT.</h3>
            <center> <h4 style="color: #3c763d;">When you live here, you get more than a home. You get an entire neighborhood where you can live, work, shop, dine and play.</h4></center>
            <br><br>
            <center> <h4 style="color: #3c763d;">Our homes include an abundance of neighborhood retail, restaurants, office space and more. With so much convenience right at your doorstep, there's hardly a need to venture further, but the direct access to the Metro, I-495 and I-395 make downtown DC, Old Town Alexandria and more easily accessible.</h4></center>
        </div>
       
    </div>
</section>







<p id="notice"><%= notice %></p>

<h1>Listing Shopabouts</h1>

<table>
  <thead>
    <tr>
      <th>Shopname</th>
      <th>Aboutinfo</th>
      <th>Shopmobno</th>
      <th>Shopownername</th>
      <th>Unicproductsforsale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shopabouts.each do |shopabout| %>
      <tr>
        <td><%= shopabout.id %></td>
        <td><%= shopabout.shopname %></td>
        <td><%= shopabout.aboutinfo %></td>
        <td><%= shopabout.shopmobno %></td>
        <td><%= shopabout.shopownername %></td>
        <td><%= shopabout.unicproductsforsale %></td>
        <td><%= link_to 'Show', shopabout %></td>
        <td><%= link_to 'Edit', edit_shopabout_path(shopabout) %></td>
        <td><%= link_to 'Destroy', shopabout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



 @user

<table>
  <thead>
    <tr>
      <th>Userid</th>
      
    </tr>
  </thead>

  <tbody>
    <% @user.each do |user| %>
      <tr>
        <td><%= user.id %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/privacy_policy.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>privarcy and policy</h1>
</body>
</html>

app/views/home/termandcondition.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      #map {
        height: 400px;
        width: 100%;
       }

    </style>
  </head>
  <body>
    <h3>My Google Maps Demo</h3>
    
  </body>
</html>