config/routes.rb
Rails.application.routes.draw do
  

  resources :shoplocations
  resources :shoptimings
  resources :shopphotos
  devise_for :users

  authenticated :user do
    root 'home#dashbord', as: :authenticated_root
  end
  root 'home#index'
  
 resources :shopaddresses
 resources :shopabouts

 get '/search' => "home#search"
 get '/about_us' => "home#about_us"
 get '/contact_us' => "home#contact_us"
 get '/privacy_policy' => "home#privacy_policy"
 get '/termandcondition' => "home#termandcondition"
  

  

end

app/models/shopphoto.rb
# == Schema Information
#
# Table name: shopphotos
#
#  id                       :integer          not null, primary key
#  img_name                 :string(255)
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  user_id                  :integer
#  shopphoto_file_name      :string(255)
#  shopphoto_content_type   :string(255)
#  shopphoto_file_size      :integer
#  shopphoto_updated_at     :datetime
#  shopphoto1_file_name     :string(255)
#  shopphoto1_content_type  :string(255)
#  shopphoto1_file_size     :integer
#  shopphoto1_updated_at    :datetime
#  shopphoto2_file_name     :string(255)
#  shopphoto2_content_type  :string(255)
#  shopphoto2_file_size     :integer
#  shopphoto2_updated_at    :datetime
#  shopphoto3_file_name     :string(255)
#  shopphoto3_content_type  :string(255)
#  shopphoto3_file_size     :integer
#  shopphoto3_updated_at    :datetime
#  unicproimg1_file_name    :string(255)
#  unicproimg1_content_type :string(255)
#  unicproimg1_file_size    :integer
#  unicproimg1_updated_at   :datetime
#  unicproimg2_file_name    :string(255)
#  unicproimg2_content_type :string(255)
#  unicproimg2_file_size    :integer
#  unicproimg2_updated_at   :datetime
#

class Shopphoto < ActiveRecord::Base
	belongs_to :user


	has_attached_file :shopphoto, styles: { large: "600x600",  medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	has_attached_file :shopphoto1, styles: { large: "600x600",  medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	has_attached_file :shopphoto2, styles: { large: "600x600",  medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	has_attached_file :shopphoto3, styles: { large: "600x600",  medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	has_attached_file :unicproimg1, styles: { large: "600x600",  medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	has_attached_file :unicproimg2, styles: { large: "600x600",  medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :shopphoto, content_type: /\Aimage\/.*\z/
	validates_attachment_content_type :shopphoto1, content_type: /\Aimage\/.*\z/
	validates_attachment_content_type :shopphoto2, content_type: /\Aimage\/.*\z/
	validates_attachment_content_type :shopphoto3, content_type: /\Aimage\/.*\z/
	validates_attachment_content_type :unicproimg1, content_type: /\Aimage\/.*\z/
	validates_attachment_content_type :unicproimg2, content_type: /\Aimage\/.*\z/
end

app/controllers/shopphotos_controller.rb
class ShopphotosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shopphoto, only: [:show, :edit, :update, :destroy]

  # GET /shopphotos
  # GET /shopphotos.json
  def index
    @shopphotos =  current_user.shopphotos  #Shopphoto.all
     if Shopphoto.where(:user_id => current_user.id).present?
         shopphotos_path
     else
          redirect_to new_shopphoto_path
    end
  end

  # GET /shopphotos/1
  # GET /shopphotos/1.json
  def show
  end

  # GET /shopphotos/new
  def new
    @shopphoto = Shopphoto.new
  end

  # GET /shopphotos/1/edit
  def edit
    @shopphotos =  current_user.shopphotos
  end

  # POST /shopphotos
  # POST /shopphotos.json
  def create
    @shopphoto = Shopphoto.new(shopphoto_params)
    @shopphoto.user_id = current_user.id

    respond_to do |format|
      if @shopphoto.save
        format.html { redirect_to shopphotos_path, notice: 'Shopphoto was successfully created.' }
        format.json { render :show, status: :created, location: shopphotos_path }
      else
        format.html { render :new }
        format.json { render json: shopphotos_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopphotos/1
  # PATCH/PUT /shopphotos/1.json
  def update
    respond_to do |format|
      if @shopphoto.update(shopphoto_params)
        format.html { redirect_to shopphotos_path, notice: 'Shopphoto was successfully updated.' }
        format.json { render :show, status: :ok, location: shopphotos_path }
      else
        format.html { render :edit }
        format.json { render json: shopphotos_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopphotos/1
  # DELETE /shopphotos/1.json
  def destroy
    @shopphoto.destroy
    respond_to do |format|
      format.html { redirect_to shopphotos_url, notice: 'Shopphoto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopphoto
      @shopphoto = Shopphoto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopphoto_params
      params.require(:shopphoto).permit(:img_name, :shopphoto,:shopphoto1, :shopphoto2, :shopphoto3, :unicproimg1, :unicproimg2, :user_id)
    end
end

app/helpers/shopphotos_helper.rb
module ShopphotosHelper
end

app/views/shopphotos/_form.html.erb
<!-- 
<%= form_for @shopphoto,  html: { multipart: true } do |f| %>
  <% if @shopphoto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopphoto.errors.count, "error") %> prohibited this shopphoto from being saved:</h2>

      <ul>
      <% @shopphoto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :img_name %><br>
    <%= f.text_field :img_name %>
  </div>
  <div class="field">
    <%= f.label :shopphoto %><br>
   <%= f.file_field :shopphoto %>
  </div>

  <div class="field">
    <%= f.label :shopphoto1 %><br>
   <%= f.file_field :shopphoto1 %>
  </div>
  <div class="field">
    <%= f.label :shopphoto2 %><br>
   <%= f.file_field :shopphoto2 %>
  </div>
  <div class="field">
    <%= f.label :shopphoto3 %><br>
   <%= f.file_field :shopphoto3 %>
  </div>
  <div class="field">
    <%= f.label :unicproimg1 %><br>
   <%= f.file_field :unicproimg1 %>
  </div>
  <div class="field">
    <%= f.label :unicproimg2 %><br>
   <%= f.file_field :unicproimg2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 -->


<section class="inner-banner light-black-bg">
  <div class="auto-container clearfix">
    <div class="title pull-left">
      <h3>Update Shop Photo </h3>
    </div>
    <div class="breadcumb pull-right">
      <ul class="list-inline">
        <li><a href="/">Dashboard</a></li>
        <li><span>Update Shop Photo </span></li>
      </ul>
    </div>
  </div>
</section>


<section class="get-a-qoute sec-padding">
  <div class="auto-container">
  <div class="row">
   <%= form_for @shopphoto,  html: { multipart: true } do |f| %>
  <% if @shopphoto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopphoto.errors.count, "error") %> prohibited this shopphoto from being saved:</h2>

      <ul>
      <% @shopphoto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <% @shopphotos.each do |shopphoto| %>
      <div class="col-sm-offset-1 col-md-5">
        <div class="form-group">
          
            <%= image_tag shopphoto.shopphoto.url(:thumb) %>
             <%= f.file_field :shopphoto %>
        </div>
        <div class="form-group">
        <%= image_tag shopphoto.shopphoto1.url(:thumb) %>
            <%= f.file_field :shopphoto1 %>
        </div>
        <div class="form-group">
        <%= image_tag shopphoto.shopphoto2.url(:thumb) %>
             <%= f.file_field :shopphoto2 %>
        </div>
      </div>
     
      <div class="col-md-5">
        <div class="form-group">
        <%= image_tag shopphoto.shopphoto3.url(:thumb) %>
            <%= f.file_field :shopphoto3 %>
        </div>
        <div class="form-group">
        <%= image_tag shopphoto.unicproimg1.url(:thumb) %>
           <%= f.file_field :unicproimg1 %>
        </div>
        <div class="form-group">
        <%= image_tag shopphoto.unicproimg2.url(:thumb) %>
        <%= f.file_field :unicproimg2 %>
        </div>
         <div class="form-group clearfix">
         <%= f.submit class:" btn btn-lg btn-primary", tabindex:"6"%>
         <%= link_to 'Back', shopphotos_path, class:" btn btn-lg button", tabindex:"7" %>
         
        </div>
      </div>
     <% end %>
      <!-- <div class=" col-sm-offset-4 col-md-12">
       
      </div> -->
     
     <% end %>
    </div>
  </div>
</section>

app/views/shopphotos/edit.html.erb
<!-- <h1>Editing Shopphoto</h1> -->

<%= render 'form' %>
<!-- 
<%= link_to 'Show', @shopphoto %> |
<%= link_to 'Back', shopphotos_path %> -->

app/views/shopphotos/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Listing Shopphotos</h1>

<table>
  <thead>
    <tr>
      <th>Img name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shopphotos.each do |shopphoto| %>
      <tr>
        <td><%= shopphoto.img_name %></td>
        <td><%= image_tag shopphoto.shopphoto.url(:thumb) %></td>
        <td><%= image_tag shopphoto.shopphoto1.url(:thumb) %></td>
        <td><%= image_tag shopphoto.shopphoto2.url(:thumb) %></td>
        <td><%= image_tag shopphoto.shopphoto3.url(:thumb) %></td>
        <td><%= image_tag shopphoto.unicproimg1.url(:thumb) %></td>
        <td><%= image_tag shopphoto.unicproimg2.url(:thumb) %></td>
       <td><%= link_to 'Show', shopphoto %></td> 
        <td><%= link_to 'Edit', edit_shopphoto_path(shopphoto) %></td>
        <td><%= link_to 'Destroy', shopphoto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopphoto', new_shopphoto_path %>
 -->


 <section class="inner-banner light-black-bg">
  <div class="auto-container clearfix">
    <div class="title pull-left">
      <h3>Shop Photo.</h3>
    </div>
    <div class="breadcumb pull-right">
      <ul class="list-inline">
        <li><a href="/">Dashboard</a></li>
        <li><span>Shop Photo.</span></li>
      </ul>
    </div>
  </div>
</section>

 <% @shopphotos.each do |shopphoto| %>
<section class="case-study-3-col sec-padding">
  <div class="auto-container">
  
    <div class="row filter-layout masonary-layout">
      <div class="col-md-4 col-sm-4 col-xs-12 filter-item ecommerce featured">
        <div class="single-case-study">
          <div class="img-box">
           <%= image_tag shopphoto.shopphoto.url(:large) %>
            <div class="overlay">
              <div class="box">
                <div class="content">
                  <!-- <a href="case-study-details.html"><i class="fa fa-expand"></i></a> -->
                </div>
              </div>
            </div>
          </div>          
        </div><!-- /.single-case-study -->
      </div><!-- /.col-md-6 filter-item -->
      <div class="col-md-4 col-sm-4 col-xs-12 filter-item seo technology">
        <div class="single-case-study">
          <div class="img-box">
            <%= image_tag shopphoto.shopphoto1.url(:large) %>
            <div class="overlay">
              <div class="box">
                <div class="content">
                 <!--  <a href="case-study-details.html"><i class="fa fa-expand"></i></a> -->
                </div>
              </div>
            </div>
          </div>          
        </div><!-- /.single-case-study -->
      </div><!-- /.col-md-6 filter-item -->
      <div class="col-md-4 col-sm-4 col-xs-12 filter-item ecommerce featured">
        <div class="single-case-study">
          <div class="img-box">
            <%= image_tag shopphoto.shopphoto2.url(:large) %>
            <div class="overlay">
              <div class="box">
                <div class="content">
                  <!-- <a href="case-study-details.html"><i class="fa fa-expand"></i></a> -->
                </div>
              </div>
            </div>
          </div>          
        </div><!-- /.single-case-study -->
      </div><!-- /.col-md-6 filter-item -->

         <div class="col-md-4 col-sm-4 col-xs-12 filter-item ecommerce featured">
        <div class="single-case-study">
          <div class="img-box">
            <%= image_tag shopphoto.shopphoto3.url(:large) %>
            <div class="overlay">
              <div class="box">
                <div class="content">
                  <!-- <a href="case-study-details.html"><i class="fa fa-expand"></i></a> -->
                </div>
              </div>
            </div>
          </div>          
        </div><!-- /.single-case-study -->
      </div><!-- /.col-md-6 filter-item -->
         <div class="col-md-4 col-sm-4 col-xs-12 filter-item ecommerce featured">
        <div class="single-case-study">
          <div class="img-box">
            <%= image_tag shopphoto.unicproimg1.url(:large) %>
            <div class="overlay">
              <div class="box">
                <div class="content">
                  <!-- <a href="case-study-details.html"><i class="fa fa-expand"></i></a> -->
                </div>
              </div>
            </div>
          </div>          
        </div><!-- /.single-case-study -->
      </div><!-- /.col-md-6 filter-item -->
         <div class="col-md-4 col-sm-4 col-xs-12 filter-item ecommerce featured">
        <div class="single-case-study">
          <div class="img-box">
            <%= image_tag shopphoto.unicproimg2.url(:large) %>
            <div class="overlay">
              <div class="box">
                <div class="content">
                  <!-- <a href="case-study-details.html"><i class="fa fa-expand"></i></a> -->
                </div>
              </div>
            </div>
          </div>          
        </div><!-- /.single-case-study -->
      </div><!-- /.col-md-6 filter-item -->
   
     
    </div><!-- /.row filter-layout -->

  </div><!-- /.auto-container -->



   <div class="col-md-offset-4 col-md-6">
        <%= link_to 'Update Shop Photo', edit_shopphoto_path(shopphoto), class:" btn btn-lg btn-primary" %>
      </div>
</section>

  <% end %>

app/views/shopphotos/new.html.erb
<!-- <h1>New Shopphoto</h1> -->

<%= render 'form' %>
<!-- 
<%= link_to 'Back', shopphotos_path %> -->

app/views/shopphotos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Img name:</strong>
  <%= @shopphoto.img_name %>
</p>

<%= link_to 'Edit', edit_shopphoto_path(@shopphoto) %> |
<%= link_to 'Back', shopphotos_path %>