config/routes.rb
Rails.application.routes.draw do
  

  resources :shoplocations
  resources :shoptimings
  resources :shopphotos
  devise_for :users

  authenticated :user do
    root 'home#dashbord', as: :authenticated_root
  end
  root 'home#index'
  
 resources :shopaddresses
 resources :shopabouts

 get '/search' => "home#search"
 get '/about_us' => "home#about_us"
 get '/contact_us' => "home#contact_us"
 get '/privacy_policy' => "home#privacy_policy"
 get '/termandcondition' => "home#termandcondition"
  

  

end

app/models/shoplocation.rb
# == Schema Information
#
# Table name: shoplocations
#
#  id         :integer          not null, primary key
#  location   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Shoplocation < ActiveRecord::Base
	belongs_to :user
end

app/controllers/shoplocations_controller.rb
class ShoplocationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shoplocation, only: [:show, :edit, :update, :destroy]

  # GET /shoplocations
  # GET /shoplocations.json
  def index
    @shoplocations = current_user.shoplocations  #Shoplocation.all
    if Shoplocation.where(:user_id => current_user.id).present?
         shoplocations_path
     else
          redirect_to new_shoplocation_path
    end 
  end

  # GET /shoplocations/1
  # GET /shoplocations/1.json
  def show
  end

  # GET /shoplocations/new
  def new
    @shoplocation = Shoplocation.new
  end

  # GET /shoplocations/1/edit
  def edit
  end

  # POST /shoplocations
  # POST /shoplocations.json
  def create
    @shoplocation = params[:location]
    @shoplocation = Shoplocation.new(shoplocation_params)
    @shoplocation.user_id = current_user.id
    respond_to do |format|
      if @shoplocation.save
        format.html { redirect_to shoplocations_path, notice: 'Shoplocation was successfully created.' }
        format.json { render :show, status: :created, location: shoplocations_path }
      else
        format.html { render :new }
        format.json { render json: shoplocations_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoplocations/1
  # PATCH/PUT /shoplocations/1.json
  def update
    respond_to do |format|
      if @shoplocation.update(shoplocation_params)
        format.html { redirect_to shoplocations_path, notice: 'Shoplocation was successfully updated.' }
        format.json { render :show, status: :ok, location: shoplocations_path }
      else
        format.html { render :edit }
        format.json { render json: shoplocations_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoplocations/1
  # DELETE /shoplocations/1.json
  def destroy
    @shoplocation.destroy
    respond_to do |format|
      format.html { redirect_to shoplocations_url, notice: 'Shoplocation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoplocation
      @shoplocation = Shoplocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoplocation_params
      params.require(:shoplocation).permit(:location, :user_id)
    end
end

app/helpers/shoplocations_helper.rb
module ShoplocationsHelper
end

app/views/shoplocations/_form.html.erb
<!-- 

<%= form_for(@shoplocation) do |f| %>
  <% if @shoplocation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shoplocation.errors.count, "error") %> prohibited this shoplocation from being saved:</h2>

      <ul>
      <% @shoplocation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 -->
<style>
      #map {
        height: 400px;
        width: 100%;
       }

    </style>

 <section class="inner-banner light-black-bg">
  <div class="auto-container clearfix">
    <div class="title pull-left">
      <h3>Update Shop Locations.</h3>
    </div>
    <div class="breadcumb pull-right">
      <ul class="list-inline">
        <li><a href="/">Dashboard</a></li>
        <li><span>Update Shop Locations.</span></li>
      </ul>
    </div>
  </div>
</section>

<section class="real-time-analytics sec-padding">
  <div class="auto-container">
    <div class="row">

      <div class="col-md-12">
          <div id="map"></div>

      </div>
      
    </div>
  </div>
</section>


    <script>
                      var marker={};
                      var map;
                      function initMap() {
                       var wakad = { lat: 18.59860, lng: 73.76387 };

                        map = new google.maps.Map(document.getElementById('map'), {
                          zoom: 14,
                          center: wakad
                        });
                       /*marker = new google.maps.Marker({
                          position: wakad,
                          map: map
                        }); */
                        // This event listener calls addMarker() when the map is clicked.
                            google.maps.event.addListener(map, 'click', function(event) {
                                //marker={};
                              addMarker(event.latLng);
                            });                                              

                      }
                        

                       // Adds a marker to the map.
                        function addMarker(location) {
                          // Add the marker at the clicked location, and add the next-available label
                          // from the array of alphabetical characters.

                        google.maps.event.addListener(marker, 'click', function(event) {
                            this.setMap(null);
                            });
                          marker = new google.maps.Marker({
                            position: location,
                            
                            map: map
                          });
                          var location = JSON.stringify(marker.position);

                         
                        }

                    </script>
<%= link_to "Go!", shoplocations_path(), :with => "'location='+ location"  %>
   <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCP8_quTmFw-Wl5rSAEUeoKPeOu0LIxd08&callback=initMap">
    </script>      

app/views/shoplocations/edit.html.erb
<!-- <h1>Editing Shoplocation</h1> -->

<%= render 'form' %>
<!-- 
<%= link_to 'Show', @shoplocation %> |
<%= link_to 'Back', shoplocations_path %> -->

app/views/shoplocations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shoplocations</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shoplocations.each do |shoplocation| %>
      <tr>
        <td><%= shoplocation.location %></td>
        <td><%= link_to 'Show', shoplocation %></td>
        <td><%= link_to 'Edit', edit_shoplocation_path(shoplocation) %></td>
        <td><%= link_to 'Destroy', shoplocation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shoplocation', new_shoplocation_path %> 

 

app/views/shoplocations/new.html.erb
<!-- <h1>New Shoplocation</h1> -->

<%= render 'form' %>
<!-- 
<%= link_to 'Back', shoplocations_path %> -->

app/views/shoplocations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @shoplocation.location %>
</p>

<%= link_to 'Edit', edit_shoplocation_path(@shoplocation) %> |
<%= link_to 'Back', shoplocations_path %>